### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by mpbish** [zichy/vicco#2]
Hi, I love this application, thank you for developing. 

I'm not a coder, but have a couple of feature requests. Or if you could point me on how to do the following that would be great.

1. Store all of the post content in a single folder rather than creating a new folder each time. Preferably in a single file too.

2. Http links in the content clickable rather than plain text.

I know you probably weren't expecting feature requests, but any support on this would be great!

Thanks.

**Comment by zichy** [comment]
Thanks for your feedback!

1. That's a great idea, but I have no idea how to do that to be honest. Maybe I'll get into some trial and error if I find the time.
2. You can make links clickable with `[https://example.org]` or `[title](https://example.org)` (see [text formatting](https://github.com/zichy/vicco#text-formatting)).
